version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

issues:
  exclude-dirs:
    - bin
